name: Node.js CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
      env:
        MESSAGE_USERNAME: ${{ secrets.MESSAGE_USERNAME }}
        MESSAGE_API_KEY: ${{ secrets.MESSAGE_API_KEY }}
        MESSAGE_BASE_URL: ${{ secrets.MESSAGE_BASE_URL }}
